name: cbt_software
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  file_picker: ^8.0.0
  csv: ^6.0.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2  
  network_info_plus: ^6.0.0
  uuid: ^4.4.0
  json_annotation: ^4.9.0
  http: ^1.6.0
  docx_to_text: ^1.0.1
  printing: ^5.14.2
  # pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
  assets:
    - assets/web/
    